export interface Word {
  da: string
  en: string
}

export const wordList: Word[] = [
  { da: 'og', en: 'and' }, { da: 'i', en: 'in' }, { da: 'en', en: 'a/an' }, { da: 'at', en: 'to/that' }, { da: 'den', en: 'it/the' },
  { da: 'til', en: 'to' }, { da: 'på', en: 'on' }, { da: 'af', en: 'of' }, { da: 'med', en: 'with' }, { da: 'det', en: 'it' },
  { da: 'have', en: 'have' }, { da: 'for', en: 'for' }, { da: 'der', en: 'there/who' }, { da: 'kunne', en: 'can/could' }, { da: 'jeg', en: 'I' },
  { da: 'som', en: 'as/who' }, { da: 'ikke', en: 'not' }, { da: 'du', en: 'you' }, { da: 'vi', en: 'we' }, { da: 'om', en: 'about' },
  { da: 'så', en: 'so' }, { da: 'blive', en: 'become/be' }, { da: 'fra', en: 'from' }, { da: 'skulle', en: 'should/must' }, { da: 'men', en: 'but' },
  { da: 'få', en: 'get' }, { da: 'de', en: 'they' }, { da: 'ville', en: 'would/will' }, { da: 'man', en: 'one/you' }, { da: 'denne', en: 'this' },
  { da: 'eller', en: 'or' }, { da: 'også', en: 'also' }, { da: 'meget', en: 'much/very' }, { da: 'mange', en: 'many' }, { da: 'ved', en: 'at/by' },
  { da: 'han', en: 'he' }, { da: 'al', en: 'all' }, { da: 'nogen', en: 'someone/any' }, { da: 'anden', en: 'other' }, { da: 'sig', en: 'oneself' },
  { da: 'god', en: 'good' }, { da: 'hvor', en: 'where' }, { da: 'se', en: 'see' }, { da: 'stor', en: 'big' }, { da: 'komme', en: 'come' },
  { da: 'din', en: 'your' }, { da: 'år', en: 'year' }, { da: 'ny', en: 'new' }, { da: 'efter', en: 'after' }, { da: 'her', en: 'here' },
  { da: 'hvis', en: 'if/whose' }, { da: 'ud', en: 'out' }, { da: 'når', en: 'when' }, { da: 'over', en: 'over' }, { da: 'min', en: 'my' },
  { da: 'gøre', en: 'do' }, { da: 'nu', en: 'now' }, { da: 'da', en: 'then/as' }, { da: 'dag', en: 'day' }, { da: 'op', en: 'up' },
  { da: 'gå', en: 'go/walk' }, { da: 'sin', en: 'his/her own' }, { da: 'vores', en: 'our' }, { da: 'tage', en: 'take' }, { da: 'give', en: 'give' },
  { da: 'hun', en: 'she' }, { da: 'sige', en: 'say' }, { da: 'selv', en: 'self' }, { da: 'finde', en: 'find' }, { da: 'bruge', en: 'use' },
  { da: 'gang', en: 'time/occurrence' }, { da: 'lille', en: 'small' }, { da: 'hvad', en: 'what' }, { da: 'lidt', en: 'a little' }, { da: 'tid', en: 'time' },
  { da: 'deres', en: 'their' }, { da: 'lige', en: 'just/straight' }, { da: 'dansk', en: 'Danish' }, { da: 'kun', en: 'only' }, { da: 'helt', en: 'completely' },
  { da: 'end', en: 'than' }, { da: 'mand', en: 'man' }, { da: 'barn', en: 'child' }, { da: 'to', en: 'two' }, { da: 'lade', en: 'let' },
  { da: 'kvinde', en: 'woman' }, { da: 'første', en: 'first' }, { da: 'sted', en: 'place' }, { da: 'stå', en: 'stand' }, { da: 'godt', en: 'well/good' },
  { da: 'side', en: 'side/page' }, { da: 'kende', en: 'know' }, { da: 'måde', en: 'way' }, { da: 'holde', en: 'hold/keep' }, { da: 'igen', en: 'again' },
  { da: 'hjem', en: 'home' }, { da: 'tre', en: 'three' }, { da: 'liv', en: 'life' }, { da: 'tror', en: 'think/believe' }, { da: 'del', en: 'part' },
  { da: 'by', en: 'city/town' }, { da: 'land', en: 'country' }, { da: 'gennem', en: 'through' }, { da: 'ord', en: 'word' }, { da: 'ting', en: 'thing' },
  { da: 'navn', en: 'name' }, { da: 'folk', en: 'people' }, { da: 'køre', en: 'drive' }, { da: 'arbejde', en: 'work' }, { da: 'skole', en: 'school' },
  { da: 'ven', en: 'friend' }, { da: 'mad', en: 'food' }, { da: 'vand', en: 'water' }, { da: 'drikke', en: 'drink' }, { da: 'bil', en: 'car' },
  { da: 'hus', en: 'house' }, { da: 'mor', en: 'mother' }, { da: 'far', en: 'father' }, { da: 'søster', en: 'sister' }, { da: 'bror', en: 'brother' },
  { da: 'søn', en: 'son' }, { da: 'datter', en: 'daughter' }, { da: 'hund', en: 'dog' }, { da: 'kat', en: 'cat' }, { da: 'bog', en: 'book' },
  { da: 'bord', en: 'table' }, { da: 'stol', en: 'chair' }, { da: 'dør', en: 'door' }, { da: 'vindue', en: 'window' }, { da: 'værelse', en: 'room' },
  { da: 'seng', en: 'bed' }, { da: 'penge', en: 'money' }, { da: 'sko', en: 'shoe' }, { da: 'tøj', en: 'clothes' }, { da: 'morgen', en: 'morning' },
  { da: 'aften', en: 'evening' }, { da: 'nat', en: 'night' }, { da: 'uge', en: 'week' }, { da: 'måned', en: 'month' }, { da: 'time', en: 'hour' },
  { da: 'minut', en: 'minute' }, { da: 'i dag', en: 'today' }, { da: 'i morgen', en: 'tomorrow' }, { da: 'i går', en: 'yesterday' }, { da: 'altid', en: 'always' },
  { da: 'aldrig', en: 'never' }, { da: 'ofte', en: 'often' }, { da: 'nogle gange', en: 'sometimes' }, { da: 'snart', en: 'soon' }, { da: 'tidligt', en: 'early' },
  { da: 'sent', en: 'late' }, { da: 'hurtig', en: 'fast/quick' }, { da: 'langsom', en: 'slow' }, { da: 'varm', en: 'hot' }, { da: 'kold', en: 'cold' },
  { da: 'glad', en: 'happy' }, { da: 'trist', en: 'sad' }, { da: 'træt', en: 'tired' }, { da: 'sulten', en: 'hungry' }, { da: 'tørstig', en: 'thirsty' },
  { da: 'syg', en: 'sick' }, { da: 'sund', en: 'healthy' }, { da: 'gammel', en: 'old' }, { da: 'ung', en: 'young' }, { da: 'smuk', en: 'beautiful' },
  { da: 'grim', en: 'ugly' }, { da: 'nem', en: 'easy' }, { da: 'svær', en: 'difficult' }, { da: 'dyr', en: 'expensive' }, { da: 'billig', en: 'cheap' },
  { da: 'rig', en: 'rich' }, { da: 'fattig', en: 'poor' }, { da: 'stærk', en: 'strong' }, { da: 'svag', en: 'weak' }, { da: 'ren', en: 'clean' },
  { da: 'beskidt', en: 'dirty' }, { da: 'fuld', en: 'full' }, { da: 'tom', en: 'empty' }, { da: 'åben', en: 'open' }, { da: 'lukket', en: 'closed' },
  { da: 'købe', en: 'buy' }, { da: 'sælge', en: 'sell' }, { da: 'læse', en: 'read' }, { da: 'skrive', en: 'write' }, { da: 'lytte', en: 'listen' },
  { da: 'høre', en: 'hear' }, { da: 'snakke', en: 'talk' }, { da: 'tale', en: 'speak' }, { da: 'elske', en: 'love' }, { da: 'hade', en: 'hate' },
  { da: 'smile', en: 'smile' }, { da: 'grine', en: 'laugh' }, { da: 'græde', en: 'cry' }, { da: 'sove', en: 'sleep' }, { da: 'vågne', en: 'wake up' },
  { da: 'tænke', en: 'think' }, { da: 'lære', en: 'learn' }, { da: 'spørge', en: 'ask' }, { da: 'svare', en: 'answer' }, { da: 'hjælpe', en: 'help' },
]
