export interface Word {
  da: string
  en: string
}

export const wordList: Word[] = [
  { da: 'og', en: 'and' }, { da: 'i', en: 'in' }, { da: 'en', en: 'a/an' }, { da: 'at', en: 'to/that' }, { da: 'den', en: 'it/the' },
  { da: 'til', en: 'to' }, { da: 'på', en: 'on' }, { da: 'af', en: 'of' }, { da: 'med', en: 'with' }, { da: 'det', en: 'it' },
  { da: 'have', en: 'have' }, { da: 'for', en: 'for' }, { da: 'der', en: 'there/who' }, { da: 'kunne', en: 'can/could' }, { da: 'jeg', en: 'I' },
  { da: 'som', en: 'as/who' }, { da: 'ikke', en: 'not' }, { da: 'du', en: 'you' }, { da: 'vi', en: 'we' }, { da: 'om', en: 'about' },
  { da: 'så', en: 'so' }, { da: 'blive', en: 'become/be' }, { da: 'fra', en: 'from' }, { da: 'skulle', en: 'should/must' }, { da: 'men', en: 'but' },
  { da: 'få', en: 'get' }, { da: 'de', en: 'they' }, { da: 'ville', en: 'would/will' }, { da: 'man', en: 'one/you' }, { da: 'denne', en: 'this' },
  { da: 'eller', en: 'or' }, { da: 'også', en: 'also' }, { da: 'meget', en: 'much/very' }, { da: 'mange', en: 'many' }, { da: 'ved', en: 'at/by' },
  { da: 'han', en: 'he' }, { da: 'al', en: 'all' }, { da: 'nogen', en: 'someone/any' }, { da: 'anden', en: 'other' }, { da: 'sig', en: 'oneself' },
  { da: 'god', en: 'good' }, { da: 'hvor', en: 'where' }, { da: 'se', en: 'see' }, { da: 'stor', en: 'big' }, { da: 'komme', en: 'come' },
  { da: 'din', en: 'your' }, { da: 'år', en: 'year' }, { da: 'ny', en: 'new' }, { da: 'efter', en: 'after' }, { da: 'her', en: 'here' },
  { da: 'hvis', en: 'if/whose' }, { da: 'ud', en: 'out' }, { da: 'når', en: 'when' }, { da: 'over', en: 'over' }, { da: 'min', en: 'my' },
  { da: 'gøre', en: 'do' }, { da: 'nu', en: 'now' }, { da: 'da', en: 'then/as' }, { da: 'dag', en: 'day' }, { da: 'op', en: 'up' },
  { da: 'gå', en: 'go/walk' }, { da: 'sin', en: 'his/her own' }, { da: 'vores', en: 'our' }, { da: 'tage', en: 'take' }, { da: 'give', en: 'give' },
  { da: 'hun', en: 'she' }, { da: 'sige', en: 'say' }, { da: 'selv', en: 'self' }, { da: 'finde', en: 'find' }, { da: 'bruge', en: 'use' },
  { da: 'gang', en: 'time/occurrence' }, { da: 'lille', en: 'small' }, { da: 'hvad', en: 'what' }, { da: 'lidt', en: 'a little' }, { da: 'tid', en: 'time' },
  { da: 'deres', en: 'their' }, { da: 'lige', en: 'just/straight' }, { da: 'dansk', en: 'Danish' }, { da: 'kun', en: 'only' }, { da: 'helt', en: 'completely' },
  { da: 'end', en: 'than' }, { da: 'mand', en: 'man' }, { da: 'barn', en: 'child' }, { da: 'to', en: 'two' }, { da: 'lade', en: 'let' },
  { da: 'kvinde', en: 'woman' }, { da: 'første', en: 'first' }, { da: 'sted', en: 'place' }, { da: 'stå', en: 'stand' }, { da: 'godt', en: 'well/good' },
  { da: 'side', en: 'side/page' }, { da: 'kende', en: 'know' }, { da: 'måde', en: 'way' }, { da: 'holde', en: 'hold/keep' }, { da: 'igen', en: 'again' },
  { da: 'hjem', en: 'home' }, { da: 'tre', en: 'three' }, { da: 'liv', en: 'life' }, { da: 'tro', en: 'think/believe' }, { da: 'del', en: 'part' },
  { da: 'by', en: 'city/town' }, { da: 'land', en: 'country' }, { da: 'gennem', en: 'through' }, { da: 'ord', en: 'word' }, { da: 'ting', en: 'thing' },
  { da: 'navn', en: 'name' }, { da: 'folk', en: 'people' }, { da: 'køre', en: 'drive' }, { da: 'arbejde', en: 'work' }, { da: 'skole', en: 'school' },
  { da: 'ven', en: 'friend' }, { da: 'mad', en: 'food' }, { da: 'vand', en: 'water' }, { da: 'drikke', en: 'drink' }, { da: 'bil', en: 'car' },
  { da: 'hus', en: 'house' }, { da: 'mor', en: 'mother' }, { da: 'far', en: 'father' }, { da: 'søster', en: 'sister' }, { da: 'bror', en: 'brother' },
  { da: 'søn', en: 'son' }, { da: 'datter', en: 'daughter' }, { da: 'hund', en: 'dog' }, { da: 'kat', en: 'cat' }, { da: 'bog', en: 'book' },
  { da: 'bord', en: 'table' }, { da: 'stol', en: 'chair' }, { da: 'dør', en: 'door' }, { da: 'vindue', en: 'window' }, { da: 'værelse', en: 'room' },
  { da: 'seng', en: 'bed' }, { da: 'penge', en: 'money' }, { da: 'sko', en: 'shoe' }, { da: 'tøj', en: 'clothes' }, { da: 'morgen', en: 'morning' },
  { da: 'aften', en: 'evening' }, { da: 'nat', en: 'night' }, { da: 'uge', en: 'week' }, { da: 'måned', en: 'month' }, { da: 'time', en: 'hour' },
  { da: 'minut', en: 'minute' }, { da: 'i dag', en: 'today' }, { da: 'i morgen', en: 'tomorrow' }, { da: 'i går', en: 'yesterday' }, { da: 'altid', en: 'always' },
  { da: 'aldrig', en: 'never' }, { da: 'ofte', en: 'often' }, { da: 'nogle gange', en: 'sometimes' }, { da: 'snart', en: 'soon' }, { da: 'tidligt', en: 'early' },
  { da: 'sent', en: 'late' }, { da: 'hurtig', en: 'fast/quick' }, { da: 'langsom', en: 'slow' }, { da: 'varm', en: 'hot' }, { da: 'kold', en: 'cold' },
  { da: 'glad', en: 'happy' }, { da: 'trist', en: 'sad' }, { da: 'træt', en: 'tired' }, { da: 'sulten', en: 'hungry' }, { da: 'tørstig', en: 'thirsty' },
  { da: 'syg', en: 'sick' }, { da: 'sund', en: 'healthy' }, { da: 'gammel', en: 'old' }, { da: 'ung', en: 'young' }, { da: 'smuk', en: 'beautiful' },
  { da: 'grim', en: 'ugly' }, { da: 'nem', en: 'easy' }, { da: 'svær', en: 'difficult' }, { da: 'dyr', en: 'expensive' }, { da: 'billig', en: 'cheap' },
  { da: 'rig', en: 'rich' }, { da: 'fattig', en: 'poor' }, { da: 'stærk', en: 'strong' }, { da: 'svag', en: 'weak' }, { da: 'ren', en: 'clean' },
  { da: 'beskidt', en: 'dirty' }, { da: 'fuld', en: 'full' }, { da: 'tom', en: 'empty' }, { da: 'åben', en: 'open' }, { da: 'lukket', en: 'closed' },
  { da: 'købe', en: 'buy' }, { da: 'sælge', en: 'sell' }, { da: 'læse', en: 'read' }, { da: 'skrive', en: 'write' }, { da: 'lytte', en: 'listen' },
  { da: 'høre', en: 'hear' }, { da: 'snakke', en: 'talk' }, { da: 'tale', en: 'speak' }, { da: 'elske', en: 'love' }, { da: 'hade', en: 'hate' },
  { da: 'smile', en: 'smile' }, { da: 'grine', en: 'laugh' }, { da: 'græde', en: 'cry' }, { da: 'sove', en: 'sleep' }, { da: 'vågne', en: 'wake up' },
  { da: 'tænke', en: 'think' }, { da: 'lære', en: 'learn' }, { da: 'spørge', en: 'ask' }, { da: 'svare', en: 'answer' }, { da: 'hjælpe', en: 'help' },

  { da: 'fire', en: 'four' }, { da: 'fem', en: 'five' }, { da: 'seks', en: 'six' }, { da: 'syv', en: 'seven' }, { da: 'otte', en: 'eight' },
  { da: 'ni', en: 'nine' }, { da: 'ti', en: 'ten' }, { da: 'rød', en: 'red' }, { da: 'blå', en: 'blue' }, { da: 'grøn', en: 'green' },
  { da: 'gul', en: 'yellow' }, { da: 'sort', en: 'black' }, { da: 'hvid', en: 'white' }, { da: 'lilla', en: 'purple' }, { da: 'orange', en: 'orange' },
  { da: 'brun', en: 'brown' }, { da: 'grå', en: 'gray' }, { da: 'mandag', en: 'Monday' }, { da: 'tirsdag', en: 'Tuesday' }, { da: 'onsdag', en: 'Wednesday' },
  { da: 'torsdag', en: 'Thursday' }, { da: 'fredag', en: 'Friday' }, { da: 'lørdag', en: 'Saturday' }, { da: 'søndag', en: 'Sunday' }, { da: 'forår', en: 'spring' },
  { da: 'sommer', en: 'summer' }, { da: 'efterår', en: 'autumn' }, { da: 'vinter', en: 'winter' }, { da: 'vejr', en: 'weather' }, { da: 'sol', en: 'sun' },
  { da: 'regn', en: 'rain' }, { da: 'sne', en: 'snow' }, { da: 'vind', en: 'wind' }, { da: 'sky', en: 'cloud' }, { da: 'hoved', en: 'head' },
  { da: 'hånd', en: 'hand' }, { da: 'fod', en: 'foot' }, { da: 'øje', en: 'eye' }, { da: 'øre', en: 'ear' }, { da: 'mund', en: 'mouth' },
  { da: 'næse', en: 'nose' }, { da: 'hår', en: 'hair' }, { da: 'mave', en: 'stomach' }, { da: 'ryg', en: 'back' }, { da: 'tak', en: 'thanks' },
  { da: 'undskyld', en: 'sorry' }, { da: 'ja', en: 'yes' }, { da: 'nej', en: 'no' }, { da: 'hej', en: 'hi' }, { da: 'farvel', en: 'goodbye' },
  { da: 'velkommen', en: 'welcome' }, { da: 'måske', en: 'maybe' }, { da: 'venstre', en: 'left' }, { da: 'højre', en: 'right' }, { da: 'nord', en: 'north' },
  { da: 'syd', en: 'south' }, { da: 'øst', en: 'east' }, { da: 'vest', en: 'west' }, { da: 'telefon', en: 'phone' }, { da: 'computer', en: 'computer' },
  { da: 'avis', en: 'newspaper' }, { da: 'brev', en: 'letter' }, { da: 'nøgle', en: 'key' }, { da: 'taske', en: 'bag' }, { da: 'paraply', en: 'umbrella' },
  { da: 'briller', en: 'glasses' }, { da: 'spise', en: 'eat' }, { da: 'lave', en: 'make' }, { da: 'spille', en: 'play' }, { da: 'synge', en: 'sing' },
  { da: 'danse', en: 'dance' }, { da: 'rejse', en: 'travel' }, { da: 'flyve', en: 'fly' }, { da: 'svømme', en: 'swim' }, { da: 'møde', en: 'meet' },
  { da: 'vente', en: 'wait' }, { da: 'huske', en: 'remember' }, { da: 'glemme', en: 'forget' }, { da: 'betale', en: 'pay' }, { da: 'åbne', en: 'open (verb)' },
  { da: 'lukke', en: 'close (verb)' }, { da: 'kort', en: 'short' }, { da: 'lang', en: 'long' }, { da: 'høj', en: 'tall' }, { da: 'lav', en: 'low' },
  { da: 'tung', en: 'heavy' }, { da: 'let', en: 'light (weight)' }, { da: 'bedstemor', en: 'grandmother' }, { da: 'bedstefar', en: 'grandfather' }, { da: 'onkel', en: 'uncle' },
  { da: 'tante', en: 'aunt' },

  { da: 'hvem', en: 'who' }, { da: 'hvordan', en: 'how' }, { da: 'hvorfor', en: 'why' }, { da: 'hvilken', en: 'which' }, { da: 'fordi', en: 'because' },
  { da: 'før', en: 'before' }, { da: 'under', en: 'under' }, { da: 'mellem', en: 'between' }, { da: 'uden', en: 'without' }, { da: 'mod', en: 'toward' },
  { da: 'derfor', en: 'therefore' }, { da: 'bus', en: 'bus' }, { da: 'tog', en: 'train' }, { da: 'cykel', en: 'bicycle' }, { da: 'station', en: 'station' },
  { da: 'butik', en: 'shop' }, { da: 'restaurant', en: 'restaurant' }, { da: 'toilet', en: 'toilet' }, { da: 'gade', en: 'street' }, { da: 'lufthavn', en: 'airport' },
  { da: 'kaffe', en: 'coffee' }, { da: 'te', en: 'tea' }, { da: 'brød', en: 'bread' }, { da: 'mælk', en: 'milk' }, { da: 'øl', en: 'beer' },
  { da: 'vin', en: 'wine' }, { da: 'morgenmad', en: 'breakfast' }, { da: 'frokost', en: 'lunch' }, { da: 'aftensmad', en: 'dinner' }, { da: 'regning', en: 'bill' },
  { da: 'vær så god', en: 'here you are' }, { da: 'det var så lidt', en: "you're welcome" }, { da: 'jeg forstår ikke', en: "I don't understand" },
  { da: 'taler du engelsk', en: 'do you speak English?' }, { da: 'kan du hjælpe mig', en: 'can you help me?' },
  { da: 'bo', en: 'live (reside)' }, { da: 'stå op', en: 'get up' }, { da: 'sætte', en: 'put/set' }, { da: 'ligge', en: 'lie/be situated' }, { da: 'sidde', en: 'sit' },
  { da: 'vise', en: 'show' }, { da: 'forstå', en: 'understand' }, { da: 'prøve', en: 'try' }, { da: 'vælge', en: 'choose' }, { da: 'begynde', en: 'begin' },
  { da: 'slutte', en: 'finish' }, { da: 'vigtig', en: 'important' }, { da: 'klar', en: 'ready/clear' }, { da: 'fri', en: 'free (available)' },
  { da: 'optaget', en: 'busy' }, { da: 'sikker', en: 'safe/certain' }, { da: 'farlig', en: 'dangerous' }, { da: 'køkken', en: 'kitchen' },
  { da: 'badeværelse', en: 'bathroom' }, { da: 'lejlighed', en: 'apartment' }, { da: 'læge', en: 'doctor' }, { da: 'hospital', en: 'hospital' }, { da: 'apotek', en: 'pharmacy' },

  { da: 'nul', en: 'zero' }, { da: 'én', en: 'one (number)' }, { da: 'elleve', en: 'eleven' }, { da: 'tolv', en: 'twelve' }, { da: 'sekund', en: 'second' },
  { da: 'halv', en: 'half' }, { da: 'kvart', en: 'quarter' }, { da: 'januar', en: 'January' }, { da: 'februar', en: 'February' }, { da: 'marts', en: 'March' },
  { da: 'april', en: 'April' }, { da: 'maj', en: 'May' }, { da: 'juni', en: 'June' }, { da: 'juli', en: 'July' }, { da: 'august', en: 'August' },
  { da: 'september', en: 'September' }, { da: 'oktober', en: 'October' }, { da: 'november', en: 'November' }, { da: 'december', en: 'December' },
  { da: 'billet', en: 'ticket' }, { da: 'stoppested', en: 'bus stop' }, { da: 'taxa', en: 'taxi' }, { da: 'metro', en: 'metro' }, { da: 'færge', en: 'ferry' },
  { da: 'cykelsti', en: 'bike path' }, { da: 'indgang', en: 'entrance' }, { da: 'udgang', en: 'exit' }, { da: 'pris', en: 'price' }, { da: 'størrelse', en: 'size' },
  { da: 'kvittering', en: 'receipt' }, { da: 'supermarked', en: 'supermarket' }, { da: 'marked', en: 'market' }, { da: 'byttepenge', en: 'change (money)' },
  { da: 'nabo', en: 'neighbor' }, { da: 'kæreste', en: 'partner' }, { da: 'kollega', en: 'colleague' }, { da: 'gæst', en: 'guest' }, { da: 'kunde', en: 'customer' },
  { da: 'internet', en: 'internet' }, { da: 'e-mail', en: 'email' }, { da: 'websted', en: 'website' }, { da: 'medicin', en: 'medicine' }, { da: 'smerte', en: 'pain' },
  { da: 'tand', en: 'tooth' }, { da: 'arm', en: 'arm' }, { da: 'ben', en: 'leg' }, { da: 'finger', en: 'finger' }, { da: 'hjerte', en: 'heart' },
  { da: 'job', en: 'job' }, { da: 'kontor', en: 'office' }, { da: 'lærer', en: 'teacher' }, { da: 'elev', en: 'student' }, { da: 'mere', en: 'more' },
  { da: 'mindre', en: 'less' }, { da: 'mindst', en: 'least' }, { da: 'sammen', en: 'together' }, { da: 'alene', en: 'alone' }, { da: 'allerede', en: 'already' },
  { da: 'stadig', en: 'still' }, { da: 'frugt', en: 'fruit' }, { da: 'ost', en: 'cheese' }, { da: 'smør', en: 'butter' }, { da: 'æg', en: 'egg' },
  { da: 'kartoffel', en: 'potato' }, { da: 'fisk', en: 'fish' }, { da: 'godmorgen', en: 'good morning' }, { da: 'godnat', en: 'good night' },
  { da: 'vi ses', en: 'see you' }, { da: 'undskyld mig', en: 'excuse me' },
]
